#include "Level.h"
#include "SettingsMenu.h"
#include "RoomGenerator.h"
#include "jogo.h" 
#include "GameStateManager.h"
#include "Enemy.h"
#include "Items.h"
#include "AABBCollision.h"
#include "Tilesets.h" 
#include "Inventory.h"
#include "Leaderboard.h"
#include <cstdio> 
#include <cmath>  
#include <queue> 
#include <map>   
#include <algorithm> 

// items manager static variables
static ItemsManager g_ItemsManager;
static bool g_ItemsInitialized = false;
static int g_PlayerScore = 0;
static bool g_AllItemsCollectedMessageShown = false;

// global variables for the level data
static std::vector<std::unique_ptr<Room>> g_DungeonRooms;

// geometry pointers
static AEGfxVertexList* g_pUnitSquare = nullptr;
static AEGfxVertexList* g_pRectOutline = nullptr;

// entity data
// player character
static std::unique_ptr<Character> g_Character = nullptr;

// enemies
static std::vector<SimpleEnemy> g_Enemies;
static int g_Difficulty = 1;
// END ENTITY DATA

// level state
static bool g_RevealNeighbors = true;
static Room* g_BossRoom = nullptr;
static bool g_ShowWayfinder = false;
static bool g_ShowColors = false;
static bool g_ShowKeyLocation = false;
static s8 g_FontId = -1;

// Settings/Pause state
static bool s_ShowSettings = false;

// Level Transition state
static bool s_ShowLevelComplete = false;
static bool s_EnemyContact = false;

// Leaderboard state
static bool s_IsEnteringName = false;
static std::string s_CurrentName = "";
static bool s_ShowNameWarning = false;

/**
 * @brief Draws a rotated and scaled line segment between two points using a unit square mesh.
 * @param x1 The starting X coordinate.
 * @param y1 The starting Y coordinate.
 * @param x2 The ending X coordinate.
 * @param y2 The ending Y coordinate.
 * @param thickness The width of the line segment.
 * @param r Red color value (0.0 to 1.0).
 * @param g Green color value (0.0 to 1.0).
 * @param b Blue color value (0.0 to 1.0).
 * @param a Alpha (transparency) value (0.0 to 1.0).
 */
static void DrawLineSegment(float x1, float y1, float x2, float y2, float thickness, float r, float g, float b, float a)
{
	float dx = x2 - x1;
	float dy = y2 - y1;
	float dist = sqrtf(dx * dx + dy * dy);
	float angle = atan2f(dy, dx);
	float midX = (x1 + x2) / 2.0f;
	float midY = (y1 + y2) / 2.0f;

	AEMtx33 scale, rot, trans, transform;
	AEMtx33Scale(&scale, dist, thickness);
	AEMtx33Rot(&rot, angle);
	AEMtx33Trans(&trans, midX, midY);

	AEMtx33Concat(&transform, &rot, &scale);
	AEMtx33Concat(&transform, &trans, &transform);

	AEGfxSetRenderMode(AE_GFX_RM_COLOR);
	AEGfxSetColorToMultiply(r, g, b, a);
	AEGfxSetTransform(transform.m);
	AEGfxMeshDraw(g_pUnitSquare, AE_GFX_MDM_TRIANGLES);
}

/**
 * @brief Calculates the shortest path between two rooms using Breadth-First Search (BFS).
 * @param startRoom Pointer to the room where the search begins.
 * @param targetRoom Pointer to the destination room.
 * @return A vector of 2D coordinates representing the centers of the rooms along the path.
 * Returns an empty vector if no path is found.
 */
static std::vector<AEVec2> GetPathToBoss(Room* startRoom, Room* targetRoom)
{
	std::vector<AEVec2> pathPoints;
	if (!startRoom || !targetRoom) return pathPoints;

	std::queue<Room*> frontier;
	frontier.push(startRoom);
	std::map<Room*, Room*> cameFrom;
	cameFrom[startRoom] = nullptr;
	Room* current = nullptr;

	while (!frontier.empty())
	{
		current = frontier.front();
		frontier.pop();
		if (current == targetRoom) break;

		int midX = current->tileCountX / 2;
		int midY = current->tileCountY / 2;

		for (Room* next : current->GetNeighbours())
		{
			if (cameFrom.find(next) == cameFrom.end())
			{
				bool hasDoor = false;
				AEVec2 currentCenter = current->rect.GetCenter();
				AEVec2 nextCenter = next->rect.GetCenter();

				if (nextCenter.y > currentCenter.y) { if (current->tileMap[0][midX] == 0) hasDoor = true; }
				else if (nextCenter.y < currentCenter.y) { if (current->tileMap[current->tileCountY - 1][midX] == 0) hasDoor = true; }
				else if (nextCenter.x > currentCenter.x) { if (current->tileMap[midY][current->tileCountX - 1] == 0) hasDoor = true; }
				else if (nextCenter.x < currentCenter.x) { if (current->tileMap[midY][0] == 0) hasDoor = true; }

				if (hasDoor)
				{
					frontier.push(next);
					cameFrom[next] = current;
				}
			}
		}
	}

	if (current == targetRoom)
	{
		Room* step = targetRoom;
		while (step != nullptr)
		{
			pathPoints.push_back(step->rect.GetCenter());
			step = cameFrom[step];
		}
		std::reverse(pathPoints.begin(), pathPoints.end());
	}
	return pathPoints;
}

/**
 * @brief Checks if a specific tile is accessible from a starting tile using Breadth-First Search (BFS).
 * This prevents items, keys, and enemies from spawning inside closed-off wall structures generated by the procedural room templates. It ensures a valid walking path exists.
 * @param room    Pointer to the room containing the tilemap to check.
 * @param startX  The X grid coordinate to start the pathfinding from (usually 8, the room center).
 * @param startY  The Y grid coordinate to start the pathfinding from (usually 8, the room center).
 * @param targetX The target X grid coordinate to test for reachability.
 * @param targetY The target Y grid coordinate to test for reachability.
 * @return true   If a valid walking path exists from the start tile to the target tile.
 * @return false  If the target is a wall, out of bounds, or completely enclosed by walls.
 */
static bool IsTileReachable(Room* room, int startX, int startY, int targetX, int targetY)
{
	// If the target is a wall, it's obviously unreachable
	if (room->tileMap[targetY][targetX] != 0) return false;

	std::queue<std::pair<int, int>> frontier;
	bool visited[16][16] = { false };

	frontier.push({ startX, startY });
	visited[startY][startX] = true;

	int dx[] = { 0, 0, 1, -1 };
	int dy[] = { 1, -1, 0, 0 };

	while (!frontier.empty())
	{
		auto curr = frontier.front();
		frontier.pop();

		if (curr.first == targetX && curr.second == targetY) return true;

		for (int i = 0; i < 4; ++i)
		{
			int nx = curr.first + dx[i];
			int ny = curr.second + dy[i];

			// Check bounds and ensure it's a floor tile (0)
			if (nx >= 0 && nx < 16 && ny >= 0 && ny < 16)
			{
				if (room->tileMap[ny][nx] == 0 && !visited[ny][nx])
				{
					visited[ny][nx] = true;
					frontier.push({ nx, ny });
				}
			}
		}
	}
	return false; // Completely blocked off
}

void Level_Load()
{
	AEGfxMeshStart();
	AEGfxTriAdd(-0.5f, -0.5f, 0xFFFFFFFF, 0.0f, 1.0f, 0.5f, -0.5f, 0xFFFFFFFF, 1.0f, 1.0f, -0.5f, 0.5f, 0xFFFFFFFF, 0.0f, 0.0f);
	AEGfxTriAdd(0.5f, -0.5f, 0xFFFFFFFF, 1.0f, 1.0f, 0.5f, 0.5f, 0xFFFFFFFF, 1.0f, 0.0f, -0.5f, 0.5f, 0xFFFFFFFF, 0.0f, 0.0f);
	g_pUnitSquare = AEGfxMeshEnd();

	AEGfxMeshStart();
	AEGfxVertexAdd(-0.5f, -0.5f, 0xFFFFFFFF, 0.0f, 1.0f);
	AEGfxVertexAdd(0.5f, -0.5f, 0xFFFFFFFF, 1.0f, 1.0f);
	AEGfxVertexAdd(0.5f, 0.5f, 0xFFFFFFFF, 1.0f, 0.0f);
	AEGfxVertexAdd(-0.5f, 0.5f, 0xFFFFFFFF, 0.0f, 0.0f);
	AEGfxVertexAdd(-0.5f, -0.5f, 0xFFFFFFFF, 0.0f, 1.0f);
	g_pRectOutline = AEGfxMeshEnd();

	g_FontId = AEGfxCreateFont("Assets/exo2-regular.ttf", 20);
	if (g_FontId < 0) g_FontId = AEGfxCreateFont("Assets\\exo2-regular.ttf", 20);

	// Initialize items graphics (AFTER engine is ready)
	g_ItemsManager.InitializeGraphics();
	g_Inventory.Load();  // ADD THIS

	// Load shared settings menu resources
	SettingsMenu_Load();
}

void Level_Init()
{
	// If just came from the Main Menu or hitting Restart, reset the timer
	if (gGameStatePrev == GS_MAINMENU || gGameStateCurr == GS_RESTART) {
		g_RunTimer = 0.0f;
	}

	// Calculate current level mathematically
	g_CurrentRunLevel = (gGameStateCurr - GS_LEVEL1) + 1;

	RoomGenerator generator;
	g_DungeonRooms = generator.Generate(3072, 3072, 512);

	Room* startRoom = nullptr;
	g_BossRoom = nullptr;

	for (const auto& room : g_DungeonRooms)
	{
		if (room->type == RoomType::Start) startRoom = room.get();
		else if (room->type == RoomType::Boss) g_BossRoom = room.get();
	}

	if (startRoom)
	{
		float tileSize = startRoom->rect.width() / 16.0f;
		int startGridX = static_cast<int>(startRoom->rect.GetCenter().x / tileSize);
		int startGridY = static_cast<int>(startRoom->rect.GetCenter().y / tileSize);

		g_Character = std::make_unique<Character>(startGridX, startGridY, tileSize);

		// Calculate shrink factor based on current level
		int currentLevelNum = 1;
		if (gGameStateCurr == GS_LEVEL2) currentLevelNum = 2;
		else if (gGameStateCurr == GS_LEVEL3) currentLevelNum = 3;
		else if (gGameStateCurr == GS_LEVEL4) currentLevelNum = 4;
		else if (gGameStateCurr == GS_LEVEL5) currentLevelNum = 5;
		else if (gGameStateCurr == GS_LEVEL6) currentLevelNum = 6;

		// Start at 1.0 (100%), and shrink by 10% (0.1f) for every level completed
		float shrinkFactor = 1.0f - ((currentLevelNum - 1) * 0.1f);

		// Safety Net: Cap the maximum shrinkage so the game doesn't become literally unplayable!
		if (shrinkFactor < 0.4f) shrinkFactor = 0.4f;

		// Apply the shrinkage to the player BEFORE loading the mesh
		g_Character->visionMultiplier = shrinkFactor;

		g_Character->Load();
		startRoom->isDiscovered = true;

		if (g_RevealNeighbors)
		{
			for (auto* neighbor : startRoom->GetNeighbours())
			{
				if (neighbor) neighbor->isDiscovered = true;
			}
		}
	}

	// --- SPAWN ENEMIES ---
	g_Enemies.clear();

	int totalEnemiesToSpawn = Random::Range(1, 4);
	int spawnedCount = 0;

	while (spawnedCount < totalEnemiesToSpawn)
	{
		int roomIdx = Random::Range(0, (int)g_DungeonRooms.size() - 1);
		auto& room = g_DungeonRooms[roomIdx];

		if (room->type == RoomType::Start) continue;

		int randCol = Random::Range(1, 14);
		int randRow = Random::Range(1, 14);

		// Use IsTileReachable so enemies don't spawn trapped inside boxes
		if (IsTileReachable(room.get(), 8, 8, randCol, randRow))
		{
			float spawnX = room->rect.left + (randCol * room->tileSize) + (room->tileSize * 0.5f);
			float spawnY = room->rect.top - (randRow * room->tileSize) - (room->tileSize * 0.5f);

			SimpleEnemy newEnemy;
			newEnemy.Load();
			newEnemy.SetPosition(spawnX, spawnY);

			int diceRoll = Random::Range(1, 6);
			newEnemy.SetChaseDuration(10.0f + static_cast<float>(diceRoll) * 5.0f);
			newEnemy.currentState = EnemyState::PATROL;

			g_Enemies.push_back(newEnemy);
			spawnedCount++;
		}
	}
	s_EnemyContact = false;

	if (!g_ItemsInitialized)
	{
		// --- SPAWN REGULAR ITEMS ---
		for (const auto& room : g_DungeonRooms)
		{
			if (room->type == RoomType::Start || room->type == RoomType::Boss) continue;

			if (std::rand() % 100 < 30)
			{
				int randomType = std::rand() % 3;
				int rx = 8, ry = 8; // Default to room center

				// Try to find a safely reachable tile instead of always spawning at center
				for (int i = 0; i < 50; i++) {
					int tx = std::rand() % 16;
					int ty = std::rand() % 16;
					if (IsTileReachable(room.get(), 8, 8, tx, ty)) {
						rx = tx; ry = ty; break;
					}
				}

				float itemX = room->rect.left + (rx * room->tileSize) + (room->tileSize * 0.5f);
				float itemY = room->rect.top - (ry * room->tileSize) - (room->tileSize * 0.5f);
				g_ItemsManager.SpawnItem(itemX, itemY, (ItemType)randomType);
			}
		}

		// --- SPAWN 3 KEYS in random rooms (which does not include start and boss/end room) ---
		std::vector<Room*> eligibleRooms;
		for (const auto& room : g_DungeonRooms)
		{
			if (room->type != RoomType::Start && room->type != RoomType::Boss)
			{
				eligibleRooms.push_back(room.get());
			}
		}

		// Spawn 3 keys (they will all stack in slot 4 when collected)
		int keysSpawned = 0;
		int maxKeys = 3;

		while (keysSpawned < maxKeys && !eligibleRooms.empty())
		{
			// Pick a random room
			int randomRoomIndex = std::rand() % eligibleRooms.size();
			Room* keyRoom = eligibleRooms[randomRoomIndex];

			int attempts = 0;
			bool keyPlaced = false;

			while (!keyPlaced && attempts < 100)
			{
				int tileX = std::rand() % 16;
				int tileY = std::rand() % 16;

				// Verify the key is physically reachable from the room center
				if (IsTileReachable(keyRoom, 8, 8, tileX, tileY))
				{
					float keyX = keyRoom->rect.left + (tileX * keyRoom->tileSize) + (keyRoom->tileSize * 0.5f);
					float keyY = keyRoom->rect.top - (tileY * keyRoom->tileSize) - (keyRoom->tileSize * 0.5f);

					g_ItemsManager.SpawnItem(keyX, keyY, ItemType::KEY);
					keyPlaced = true;
					keysSpawned++;
					printf("Key %d spawned safely in room at (%f, %f)\n", keysSpawned, keyX, keyY);
				}
				attempts++;
			}

			if (!keyPlaced)
			{
				// Fallback: place at room center
				g_ItemsManager.SpawnItem(keyRoom->rect.GetCenter().x, keyRoom->rect.GetCenter().y, ItemType::KEY);
				keysSpawned++;
				printf("Key %d spawned at room center (Fallback)\n", keysSpawned);
			}
			// prevents spawning of multiple keys in same room
			eligibleRooms.erase(eligibleRooms.begin() + randomRoomIndex);
		}

		printf("Total keys spawned: %d\n", keysSpawned);

		g_ItemsInitialized = true;
	}

	g_Inventory.Init();

	s_ShowLevelComplete = false;
	s_ShowSettings = false;

	s_IsEnteringName = false;
	s_CurrentName = "";
	s_ShowNameWarning = false;

	SettingsMenu_Initialize();
}

void Level_Update()
{
	// Toggle Settings/Pause
	if (AEInputCheckTriggered(AEVK_ESCAPE))
	{
		s_ShowSettings = !s_ShowSettings;
		printf("Settings Menu: %s\n", s_ShowSettings ? "ON" : "OFF");
	}

	if (s_ShowSettings)
	{
		SettingsMenu_Update(s_ShowSettings);
		return; // Stop game logic while menu is open
	}

	if (s_IsEnteringName) {
		// Capture A-Z keys
		for (int i = AEVK_A; i <= AEVK_Z; ++i) {
			if (AEInputCheckTriggered(i)) {
				if (s_CurrentName.length() < 8) {
					s_CurrentName += (char)i;
					s_ShowNameWarning = false;
				}
				else {
					s_ShowNameWarning = true; // Tried to type more than 8!
				}
			}
		}
		// Capture Backspace to delete
		if (AEInputCheckTriggered(AEVK_BACK)) {
			if (!s_CurrentName.empty()) s_CurrentName.pop_back();
			s_ShowNameWarning = false;
		}
		// Press Enter to Save and Exit
		if (AEInputCheckTriggered(AEVK_RETURN) && !s_CurrentName.empty()) {
			LeaderboardSystem::AddRun(s_CurrentName, g_CurrentRunLevel, g_RunTimer);
			gGameStateNext = GS_MAINMENU;
		}
		return; // Stop the rest of the game from updating!
	}

	// Handle Level Complete Menu
	if (s_ShowLevelComplete) {
		if (AEInputCheckTriggered(AEVK_RETURN)) {
			if (gGameStateCurr < GS_LEVEL6) {
				gGameStateNext = (GAME_STATE)(gGameStateCurr + 1);
			}
			else {
				// Beat the game! Trigger Name Entry
				s_IsEnteringName = true;
			}
		}
		if (AEInputCheckTriggered(AEVK_BACK)) {
			// Trigger Name entry instead of instantly quitting!
			if (g_CurrentRunLevel > 1 || g_RunTimer > 10.0f) {
				s_IsEnteringName = true;
			}
			else {
				gGameStateNext = GS_MAINMENU; // Ignore short spam runs
			}
		}
		return;
	}
	if (s_EnemyContact) {
		if (AEInputCheckTriggered(AEVK_BACK)) {
			gGameStateNext = GS_MAINMENU; // Return to menu
		}
		return; // Stop normal game logic while this menu is open
	}

	float dt = (float)AEFrameRateControllerGetFrameTime();
	g_RunTimer += dt;

	// Normal Level Updates
	if (AEInputCheckTriggered(AEVK_R)) { gGameStateNext = GS_RESTART; printf("Restarting Level...\n"); }

	// If they quit early, save their progress up to this level
	//if (AEInputCheckTriggered(AEVK_Q)) {
	//	// Trigger name entry instead of instantly quitting
	//	if (g_CurrentRunLevel > 1 || g_RunTimer > 10.0f) {
	//		s_IsEnteringName = true;
	//	}
	//	else {
	//		gGameStateNext = GS_MAINMENU;
	//	}
	//}

	if (AEInputCheckTriggered(AEVK_N)) { g_RevealNeighbors = !g_RevealNeighbors; printf("Reveal Neighbors: %s\n", g_RevealNeighbors ? "ON" : "OFF"); }
	if (AEInputCheckTriggered(AEVK_M)) { g_ShowWayfinder = !g_ShowWayfinder; printf("Show Wayfinder: %s\n", g_ShowWayfinder ? "ON" : "OFF"); }
	if (AEInputCheckTriggered(AEVK_C)) { g_ShowColors = !g_ShowColors; printf("Show Colors: %s\n", g_ShowColors ? "ON" : "OFF"); }

	// Show the key's location on the map when 'K' is pressed
	if (AEInputCheckTriggered(AEVK_K))
	{
		g_ShowKeyLocation = !g_ShowKeyLocation;
		printf("Key Tracker: %s\n", g_ShowKeyLocation ? "ON" : "OFF");
	}

	// Update inventory (handles number key presses)
	g_Inventory.Update();

	if (g_Character)
	{
		// Check Exit Door Collision
		if (g_BossRoom) {
			float px = g_Character->GetWorldX();
			float py = g_Character->GetWorldY();

			// Check if player is inside the Boss/Exit Room boundaries
			if (px >= g_BossRoom->rect.left && px <= g_BossRoom->rect.right &&
				py >= g_BossRoom->rect.bottom && py <= g_BossRoom->rect.top)
			{
				if (AEInputCheckTriggered(AEVK_E)) {
					int keyCount = g_Inventory.GetKeyCount();
					if (keyCount >= 3) {
						printf("Door Unlocked! You have all 3 keys!\n");
						s_ShowLevelComplete = true; // Pause game and show the menu
					}
					else {
						printf("The door is locked. You need %d more key%s! (Slot 4: %d/3)\n",
							3 - keyCount, (3 - keyCount == 1) ? "" : "s", keyCount);
					}
				}
			}
		}

		g_Character->Update(g_DungeonRooms);

		// Make sure Character class expects a vector here now
		g_Character->UpdateAbilities(dt, g_Enemies, g_ItemsManager, g_DungeonRooms);
		g_Character->CheckItemCollection(g_ItemsManager);

		AEGfxSetCamPosition(g_Character->GetWorldX(), g_Character->GetWorldY());

		// Room Discovery
		for (auto& room : g_DungeonRooms)
		{
			// check boundary collision using the new AABB helper
			if (Collision_PointInRect(g_Character->GetWorldX(), g_Character->GetWorldY(), room->rect))
			{
				room->isDiscovered = true;
				if (g_RevealNeighbors)
				{
					for (auto* neighbor : room->GetNeighbours()) if (neighbor) neighbor->isDiscovered = true;
				}
				break;
			}
		}


		// Update Enemies and Items
		float playerWorldX = g_Character->GetWorldX();
		float playerWorldY = g_Character->GetWorldY();


		for (auto& enemy : g_Enemies)
		{
			// Update enemy AI/Movement
			enemy.Update(playerWorldX, playerWorldY, dt, g_DungeonRooms);
			float dx = playerWorldX - enemy.GetWorldX();
			float dy = playerWorldY - enemy.GetWorldY();
			float distToPlayer = dx * dx + dy * dy;
			// 625 = 25^2
			if (distToPlayer < 625) s_EnemyContact = true;
		}

		// Safely update items with the defined variables
		g_ItemsManager.Update(playerWorldX, playerWorldY, 0.0f);
	}

	// Debug: Show item count when 'I' is pressed
	if (AEInputCheckTriggered(AEVK_I))
	{
		printf("Items collected: %d/%d\n",
			g_ItemsManager.GetCollectedCount(),
			g_ItemsManager.GetTotalCount());

		printf("Uncollected items at positions:\n");
	}

}

void Level_Draw()
{
	AEGfxSetBackgroundColor(0.0f, 0.0f, 0.0f);
	AEGfxSetRenderMode(AE_GFX_RM_COLOR);

	// Draw Rooms
	for (const auto& room : g_DungeonRooms)
	{
		if (!room->isDiscovered) continue;
		const TilesetData& style = TilesetManager::Get(room->tilesetID);

		AEMtx33 scale, trans, transform;
		AEMtx33Scale(&scale, (float)room->rect.width(), (float)room->rect.height());
		AEMtx33Trans(&trans, room->rect.GetCenter().x, room->rect.GetCenter().y);
		AEMtx33Concat(&transform, &trans, &scale);
		AEGfxSetTransform(transform.m);

		if (room->type == RoomType::Boss) AEGfxSetColorToMultiply(1.0f, 0.0f, 0.0f, 1.0f);
		else if (!g_ShowColors) AEGfxSetColorToMultiply(0.5f, 0.5f, 0.5f, 1.0f);
		else
		{
			if (room->type == RoomType::Start) AEGfxSetColorToMultiply(0.0f, 1.0f, 0.0f, 1.0f);
			else AEGfxSetColorToMultiply(style.r, style.g, style.b, 1.0f);
		}
		AEGfxMeshDraw(g_pUnitSquare, AE_GFX_MDM_TRIANGLES);

		// Draw Walls
		AEGfxSetColorToMultiply(0.0f, 0.0f, 0.0f, 1.0f);
		for (int y = 0; y < room->tileCountY; ++y)
		{
			for (int x = 0; x < room->tileCountX; ++x)
			{
				if (room->tileMap[y][x] == 1)
				{
					float wx = room->rect.left + (x * room->tileSize) + (room->tileSize * 0.5f);
					float wy = room->rect.top - (y * room->tileSize) - (room->tileSize * 0.5f);
					AEMtx33Scale(&scale, room->tileSize, room->tileSize);
					AEMtx33Trans(&trans, wx, wy);
					AEMtx33Concat(&transform, &trans, &scale);
					AEGfxSetTransform(transform.m);
					AEGfxMeshDraw(g_pUnitSquare, AE_GFX_MDM_TRIANGLES);
				}
			}
		}

		if (room->type == RoomType::Boss)
		{
			float camX = g_Character ? g_Character->GetWorldX() : 0.0f;
			float camY = g_Character ? g_Character->GetWorldY() : 0.0f;
			float textX = (room->rect.GetCenter().x - camX) * 2.0f / AEGfxGetWindowWidth();
			float textY = (room->rect.GetCenter().y - camY) * 2.0f / AEGfxGetWindowHeight();
			if (g_FontId >= 0 && textX > -0.9f && textX < 0.9f && textY > -0.9f && textY < 0.9f)
				AEGfxPrint(g_FontId, (char*)"exit", textX, textY, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f);
		}
	}

	// Draw Items
// Draw Items (Now uses the official textured Draw function in Items.cpp!)
	g_ItemsManager.Draw();
	for (auto& enemy : g_Enemies)
	{
		enemy.Draw();
	}

	// --- NEW: DRAW THE DARKNESS OVERLAY HERE ---
	if (g_Character) {
		g_Character->DrawVisionOverlay();

		// Draw the Player and Abilities LAST so they sit on top of the darkness
		g_Character->DrawAbilities();
		g_Character->Draw();
	}
	// -------------------------------------------

	// Wayfinder to boss room
	if (g_ShowWayfinder && g_BossRoom && g_Character)
	{
		float px = g_Character->GetWorldX(), py = g_Character->GetWorldY();
		Room* playerRoom = nullptr;
		for (const auto& room : g_DungeonRooms)
			if (px >= room->rect.left && px <= room->rect.right && py >= room->rect.bottom && py <= room->rect.top) { playerRoom = room.get(); break; }

		if (playerRoom)
		{
			std::vector<AEVec2> path = GetPathToBoss(playerRoom, g_BossRoom);
			if (!path.empty())
			{
				DrawLineSegment(px, py, path[0].x, path[0].y, 5.0f, 1.0f, 1.0f, 0.0f, 0.5f);
				for (size_t i = 0; i < path.size() - 1; ++i)
					DrawLineSegment(path[i].x, path[i].y, path[i + 1].x, path[i + 1].y, 5.0f, 1.0f, 1.0f, 0.0f, 0.5f);
			}
		}
	}

	// Wayfinder to key location
	if (g_ShowKeyLocation && g_Character)
	{
		for (const auto& item : g_ItemsManager.GetItems())
		{
			// Using 'item.collected', 'item.x', and 'item.y' based on Items.cpp
			// Change them to isCollected/worldX if you recently renamed them.
			if (item.type == ItemType::KEY && !item.collected)
			{
				// Draw a blue line straight from the player to the key
				DrawLineSegment(
					g_Character->GetWorldX(), g_Character->GetWorldY(),
					item.x, item.y,
					5.0f, 1.0f, 0.0f, 1.0f, 0.7f // 5px thick, Purple, 70% opacity
				);

				// Draw a massive yellow highlight box around the key itself
				AEMtx33 scale, trans, transform;
				AEMtx33Scale(&scale, 120.0f, 120.0f); // Make it big enough to easily spot
				AEMtx33Trans(&trans, item.x, item.y);
				AEMtx33Concat(&transform, &trans, &scale);

				AEGfxSetRenderMode(AE_GFX_RM_COLOR);
				AEGfxSetColorToMultiply(1.0f, 1.0f, 0.0f, 1.0f); // Solid Yellow
				AEGfxSetTransform(transform.m);
				AEGfxMeshDraw(g_pRectOutline, AE_GFX_MDM_LINES_STRIP); // Use your hollow rect mesh

				break; // We found the key, no need to keep checking items
			}
		}
	}

	// Settings Overlay
	if (s_ShowSettings)
	{
		SettingsMenu_Draw(true); // Draw with "Exit to Menu" button
		// Restore camera for next frame
		if (g_Character) AEGfxSetCamPosition(g_Character->GetWorldX(), g_Character->GetWorldY());
	}

	// Draw inventory last so it appears on top
	g_Inventory.Draw();

	if (s_ShowLevelComplete)
	{
		// Draw a semi-transparent dark background
		float camX = g_Character ? g_Character->GetWorldX() : 0.0f;
		float camY = g_Character ? g_Character->GetWorldY() : 0.0f;

		AEMtx33 scale, trans, transform;
		AEMtx33Scale(&scale, 4000.0f, 4000.0f); // Make it huge to cover the screen
		AEMtx33Trans(&trans, camX, camY);
		AEMtx33Concat(&transform, &trans, &scale);

		AEGfxSetBlendMode(AE_GFX_BM_BLEND);
		AEGfxSetRenderMode(AE_GFX_RM_COLOR);
		AEGfxSetColorToMultiply(0.0f, 0.0f, 0.0f, 0.85f); // 85% opacity black
		AEGfxSetTransform(transform.m);
		AEGfxMeshDraw(g_pUnitSquare, AE_GFX_MDM_TRIANGLES);
		AEGfxSetBlendMode(AE_GFX_BM_NONE);

		// Draw the Text (Using NDC coordinates so it sticks to the screen)
		if (g_FontId >= 0) {
			AEGfxPrint(g_FontId, (char*)"LEVEL COMPLETE!", -0.2f, 0.3f, 1.5f, 0.0f, 1.0f, 0.0f, 1.0f); // Green text

			if (gGameStateCurr < GS_LEVEL6) {
				AEGfxPrint(g_FontId, (char*)"Press [ENTER] to Descend Deeper", -0.235f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f);
			}
			else {
				AEGfxPrint(g_FontId, (char*)"YOU ESCAPED THE DUNGEON!", -0.26f, 0.0f, 1.0f, 1.0f, 1.0f, 0.0f, 1.0f);
			}

			AEGfxPrint(g_FontId, (char*)"Press [BACKSPACE] to Return to Menu", -0.26f, -0.2f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f);
		}
	}

	// --- DRAW NAME ENTRY OVERLAY ---
	if (s_IsEnteringName) {
		// Draw dark background
		float camX = g_Character ? g_Character->GetWorldX() : 0.0f;
		float camY = g_Character ? g_Character->GetWorldY() : 0.0f;
		AEMtx33 scale, trans, transform;
		AEMtx33Scale(&scale, 4000.0f, 4000.0f);
		AEMtx33Trans(&trans, camX, camY);
		AEMtx33Concat(&transform, &trans, &scale);

		AEGfxSetBlendMode(AE_GFX_BM_BLEND);
		AEGfxSetRenderMode(AE_GFX_RM_COLOR);
		AEGfxSetColorToMultiply(0.0f, 0.0f, 0.0f, 0.95f); // Super dark
		AEGfxSetTransform(transform.m);
		AEGfxMeshDraw(g_pUnitSquare, AE_GFX_MDM_TRIANGLES);
		AEGfxSetBlendMode(AE_GFX_BM_NONE);

		if (g_FontId >= 0) {
			AEGfxPrint(g_FontId, (char*)"RUN OVER!", -0.148f, 0.4f, 1.5f, 1.0f, 1.0f, 1.0f, 1.0f);
			AEGfxPrint(g_FontId, (char*)"Enter Username (Max 8 Chars)", -0.22f, 0.1f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f);

			// Draw the typed name!
			std::string displayStr = "> " + s_CurrentName + " <";
			AEGfxPrint(g_FontId, (char*)displayStr.c_str(), -0.15f, -0.1f, 1.2f, 1.0f, 1.0f, 0.0f, 1.0f); // Yellow

			if (s_ShowNameWarning) {
				AEGfxPrint(g_FontId, (char*)"Maximum 8 characters reached!", -0.2f, -0.25f, 0.8f, 1.0f, 0.0f, 0.0f, 1.0f); // Red
			}

			if (!s_CurrentName.empty()) {
				AEGfxPrint(g_FontId, (char*)"Press [ENTER] to Save Run", -0.2f, -0.5f, 1.0f, 0.0f, 1.0f, 0.0f, 1.0f); // Green
			}
		}
	}

	if (s_EnemyContact)
	{
		// Draw a semi-transparent dark background
		float camX = g_Character ? g_Character->GetWorldX() : 0.0f;
		float camY = g_Character ? g_Character->GetWorldY() : 0.0f;

		AEMtx33 scale, trans, transform;
		AEMtx33Scale(&scale, 4000.0f, 4000.0f); // Make it huge to cover the screen
		AEMtx33Trans(&trans, camX, camY);
		AEMtx33Concat(&transform, &trans, &scale);

		AEGfxSetBlendMode(AE_GFX_BM_BLEND);
		AEGfxSetRenderMode(AE_GFX_RM_COLOR);
		AEGfxSetColorToMultiply(0.0f, 0.0f, 0.0f, 0.85f); // 85% opacity black
		AEGfxSetTransform(transform.m);
		AEGfxMeshDraw(g_pUnitSquare, AE_GFX_MDM_TRIANGLES);
		AEGfxSetBlendMode(AE_GFX_BM_NONE);

		// Draw the Text (Using NDC coordinates so it sticks to the screen)
		if (g_FontId >= 0) {
			AEGfxPrint(g_FontId, (char*)"You Lose", -0.2f, 0.3f, 1.5f, 1.0f, 0.0f, 0.0f, 1.0f); // Green text

			AEGfxPrint(g_FontId, (char*)"Press [BACKSPACE] to Return to Menu", -0.275f, -0.2f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f);
		}
	}
}

void Level_Free()
{
	for (auto& room : g_DungeonRooms) if (room) room->ClearNeighbours();
	g_DungeonRooms.clear();
	g_Character = nullptr;
	g_BossRoom = nullptr;
	g_ItemsInitialized = false;
}

void Level_Unload()
{
	if (g_pUnitSquare) { AEGfxMeshFree(g_pUnitSquare); g_pUnitSquare = nullptr; }
	if (g_pRectOutline) { AEGfxMeshFree(g_pRectOutline); g_pRectOutline = nullptr; }

	if (g_FontId >= 0) {
		AEGfxDestroyFont(g_FontId);
		g_FontId = -1;
	}

	SettingsMenu_Unload();

	// Release any textures or allocated data inside the player class

	for (auto& enemy : g_Enemies) {
		enemy.Unload();
	}
	g_Enemies.clear();

	// Clear the mesh ONCE at the very end
	if (g_pUnitSquare) {
		AEGfxMeshFree(g_pUnitSquare);
		g_pUnitSquare = nullptr;
	}

	g_Inventory.Unload();
	SettingsMenu_Unload();
}